### PR TITLE
1.6.0

### PR DESCRIPTION
**Pull request by moo-man**
@sladecraven @herveDarritchon 

If you have time can pull `staging` and test your fixes?

### CODE REVIEW

**Comment by herveDarritchon** [comment]
@moo-man ok, I'll have a check today and I'll give you my feedback

**Comment by LeRatierBretonnien** [comment]
@moo-man : Also today, this evening (french time)

**Comment by herveDarritchon** [comment]
@moo-man : 

test ok for me !

- [x] bug css with FF
- [x] bug /credit
- [x] feature drag'ndrop wounds healed with rest

**Comment by LeRatierBretonnien** [comment]
OK for me ( credit button, pay button, "RestRecover" localization)

**Pull request merged**
